04-pjt/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('<int:user_pk>/change_password/', views.change_password, name='change_password'),

    path("google/login/", views.google_login, name="google-login"),
    path("google/callback/", views.google_callback, name="google-callback"),

]

04-pjt/books/urls.py
from django.urls import path
from . import views


app_name = "books"
urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),
]

04-pjt/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("books/", include("books.urls")),
    path("accounts/", include("accounts.urls")),

    path('accounts/', include('allauth.urls')), # kakao 간편 로그인 위해 추가

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

04-pjt/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">  
  <title>Document</title>
  <style>
    .book-card img {
      height: 500px;
      object-fit: cover;
    }
    .book-card .card-title {
      font-size: 1rem;
      font-weight: 600;
    }
    .book-card .card-text {
      font-size: 0.9rem;
      color: #666;
    }
    .book-card .card-subtitle {
      font-size: 0.8rem;
      color: #999;
    }
    .book-card .card-body {
      display: flex;
      flex-direction: column;
    }
    .book-card .card-subtitle {
      margin-top: auto;
    }
  </style>
</head>

<body>
  <nav class="navbar bg-success navbar-expand-lg border-bottom border-body mb-4" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'books:index' %}">ThRead</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto text-end mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'books:index' %}">INDEX</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'books:create' %}">CREATE</a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:update' %}">회원정보수정</a>
            </li>
            <li class="nav-item">
              <form action="{% url 'accounts:delete' %}" method='POST'>
                {% csrf_token %}
                <input type="submit" value="회원탈퇴" class="nav-link">
              </form>
            </li>
            <li class="nav-item">
              <form action="{% url 'accounts:logout' %}" method='POST'>
                {% csrf_token %}
                <input type="submit" value="로그아웃" class="nav-link">
              </form>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:google-login' %}">구글 로그인</a>
            </li>
            {% comment %} 카카오 간편 로그인 {% endcomment %}
            {% load socialaccount %}
            <li class="nav-item">
              <a class="nav-link" type="button" onclick="location.href = '{% provider_login_url 'kakao' %}'">카카오 로그인</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  
  <div class="container">
    {% block content %}
    {% endblock content %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>